name: cryofire

channels:
  - pytorch
  - conda-forge
  - anaconda
  - jmcmurray
  - travis

dependencies:
  - python=3.7.10
  - pip
  - pytorch=1.9.0
  - torchvision=0.10.0
  - torchaudio=0.9.0
  - cudatoolkit=11.3
  - matplotlib
  - json
  - regex
  - seaborn
  - scipy
  - scikit-learn
  - tensorboard=2.5.0
  - jupyter
  - pip:
      - setuptools==59.5.0